### ISSUE TITLE
Create Map Library

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-fhwa-stol/carma-streets#12]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ x ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Create a library that is includes lanelet2 and the autware.io extensions to consume a lanelet2 osm file. This component will be responsible for translating long,lat location information into lane specific information and providing calculation about lane conflicts, distance to end of lane, and regulatory elements. 
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by dan-du-car** [comment]
This issue can be closed per the above PR merged
