### ISSUE TITLE
Adding each link lanelet id to it's conflicting lanelets set

### ISSUE THREAD

**Issue by Saeid-Solei** [usdot-fhwa-stol/carma-streets#145]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Currently, it is assumed that each link lanelet does not have a conflicting direction with itself! This means that a vehicle can enter the intersection box before its preceding vehicle from the same link lanelet leave the intersection box. This is not the intended behavior and the following vehicle must wait for the preceding vehicle to leave the intersection box. 

To address this issue, we shall add each link lanelet id to its set of conflicting lanelets.

### Carma streets version where this issue was discovered

3.11.0

### Expected behavior
Assuming two vehicles with the same link lanelet in their path, one vehicle can enter the intersection box only after the time when the other vehicle leaves the intersection box.

### Actual behavior

Assuming two vehicles with the same link lanelet in their path, one vehicle might enter the intersection box before the other vehicle leaves the intersection box.

### Steps to reproduce the actual behavior

1. Start the intersection model with a sample map.
2. Check conflicting lanelet ids for each link lanelet and see if the subject link lanelet is included in the list of conflicting lanelets.

**Comment by paulbourelly999** [comment]
Closing OBE
