### ISSUE TITLE
Add automated build and README badge for TSC Service image builds 

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-fhwa-stol/carma-streets#178]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ x ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Add automated docker builds for the tsc_service image. Also add a badge on the README page to show build status
### Carma streets version where this issue was discovered

latest
### Expected behavior
NA
### Actual behavior

NA
### Steps to reproduce the actual behavior

NA

**Comment by SaikrishnaBairamoni** [comment]
PR has been merged into develop branch 
https://github.com/usdot-fhwa-stol/carma-streets/pull/180
