### ISSUE TITLE
Remove gh-pages branch from circle ci 

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-fhwa-stol/carma-streets#201]
### Types of Issue

- [ x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

gh-pages is an orphan branch used to hold documentation. It does not need any circle ci workflows to execute on commits 
### Expected behavior
No circle ci workflows execute on gh-pages branch
### Actual behavior

Circle CI workflows fail on gh-pages branch.

**Comment by paulbourelly999** [comment]
https://discuss.circleci.com/t/cant-ignore-the-gh-pages-branch/2002

**Comment by codygarver** [comment]
Closed by #205
