### ISSUE TITLE
Message Service creating vehicle status and intent correlated messages with 0 entry lane, link lane and departure lane ID.

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-fhwa-stol/carma-streets#240]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Currently, when the message_services correlates MP MO and BSM messages into a vehicle status and intent message, during integration testing, it is assigning 0 for entry lane, link lane and departure lane. This is likely because the message service is not recognizing the vehicle in a entry lane described as part of it's intersection
### Carma streets version where this issue was discovered

Latest
### Expected behavior
Correlated VSI updates contain valid entry lane, link lane and departure lane ids
### Actual behavior

Correlated VSI updates contain all zero lane ids for entry, link, and departure. This causes the vehicle not to be scheduled.
### Steps to reproduce the actual behavior

1. Run CARMA-Streets at East Intersection
2. Start CARMA-Platform between East and West Intersection
3. Intersection Schedules will not include vehicle

**Comment by adev4a** [comment]
This issue was stemming from an error with the osm map where the defined regulatory element was added to the lanelet element.
Fixed with map updated.
