### ISSUE TITLE
Edge case: entering time from scheduling service has a large spike 

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-streets#254]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

While fixing Issue #249 It was found there is still an edge case where the entering time spikes up by around 50 seconds before 
dropping back down and allowing the vehicle to move.
Required fix will involve using collected logs to analyze and fix the issue.

![image](https://user-images.githubusercontent.com/51463994/201709605-e531d9ae-7ab4-424c-9f79-01c3e4fcf913.png)

**Comment by paulbourelly999** [comment]
Closing issue since we are not aware of any such unexplainable ET jumps in any of our recent integration or verification testing.
