### ISSUE TITLE
Sonar Scan Issue : Kafka clients

### ISSUE THREAD

**Issue by SaikrishnaBairamoni** [usdot-fhwa-stol/carma-streets#37]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Addressing the code quality issues and other issues got from the sonar cloud static metrics

### Expected behavior
sonar scan addressed should be cleared.
### Steps to reproduce the actual behavior
sonar scan reporting issue
### Related work

https://sonarcloud.io/project/issues?id=usdot-fhwa-stol_carma-streets&resolved=false

**Comment by dan-du-car** [comment]
Issue can be closed per the above merged PR.
