### ISSUE TITLE
Fix scheduling service ST estimation issues

### ISSUE THREAD

**Issue by Saeid-Solei** [usdot-fhwa-stol/carma-streets#90]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The estimated stopping time (ST) in the schedule plan is not always correct. Sometimes, the estimated ST drops to 1-3 seconds later than the current timestamp while the vehicle is still far from the stop line.

In this issue, we aim to find the source of the issue and resolve it.

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by paulbourelly999** [comment]
Scheduling Service was refactored
